version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase as $USER on $PWD
#      - curl -s "https://get.sdkman.io" | bash
#      - source "/root/.sdkman/bin/sdkman-init.sh" && sdk install java && sdk install maven
      - mvn --version
  build:
    commands:
      - echo Entered the build phase...
      # Java
      - mvn verify
      - aws s3 sync target/reports/ s3://codinginterviews.caravana.cloud/ --delete
cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.sdkman/**/*'
